/*
 * Skrypt zakladajacy wszystkie tabele, sekwencje, triggery oraz constrainty
 *
 * Historia:
 *
 * PRZEMEK   02/11/2017  -   Utworzenie skryptu
 *
 */

-- Tabela T_USER + Sekwencja
CREATE OR REPLACE TABLE T_USER 
(
  ID INTEGER PRIMARY KEY NOT NULL,
  USERNAME VARCHAR(20) NOT NULL,
  PASSWD VARCHAR(255) NOT NULL,
  PASSWD2 VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(80),
  LAST_NAME VARCHAR(80),
  EMAIL VARCHAR(255),
  APP_ROLE_ID INTEGER,
  AVATAR BLOB,
  BLOCKED VARCHAR(1),
  DELETED VARCHAR(1)
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_USER
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_USER
CREATE OR REPLACE TRIGGER TR_USER 
  BEFORE INSERT 
  ON T_USER FOR EACH ROW
BEGIN
  SET NEW.ID = S_USER.NEXTVAL;
END;
-- Unique Constraint 
ALTER TABLE T_USER
ADD CONSTRAINT CT_USER_U UNIQUE (USERNAME, EMAIL);

-- Tabela T_ROLES + Sekwencja
CREATE OR REPLACE TABLE T_ROLES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NAME VARCHAR(20) NOT NULL
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_ROLES
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_ROLES
CREATE OR REPLACE TRIGGER TR_ROLES 
  BEFORE INSERT 
  ON T_ROLES FOR EACH ROW
BEGIN
  SET NEW.ID = S_ROLES.NEXTVAL;
END;

-- Unique Constraint 
ALTER TABLE T_ROLES
ADD CONSTRAINT CT_ROLES_U UNIQUE (NAME);

-- Tabela T_GROUPS + Sekwencja
CREATE OR REPLACE TABLE T_GROUPS
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NAME VARCHAR(20) NOT NULL
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_GROUPS
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_GROUPS
CREATE OR REPLACE TRIGGER TR_GROUPS 
  BEFORE INSERT 
  ON T_GROUPS FOR EACH ROW
BEGIN
  SET NEW.ID = S_GROUPS.NEXTVAL;
END;

-- Unique Constraint 
ALTER TABLE T_GROUPS
ADD CONSTRAINT CT_GROUPS_U UNIQUE (NAME);

-- Tabela T_GROUP_ROLES
CREATE OR REPLACE TABLE T_GROUP_ROLES
(
  GROUP_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

-- Constraint na FK
ALTER TABLE T_GROUP_ROLES
ADD CONSTRAINT CT_GROUP_ROLES_GROUP_ID_FK FOREIGN KEY
(GROUP_ID) REFERENCES T_GROUPS (ID);

ALTER TABLE T_GROUP_ROLES
ADD CONSTRAINT CT_GROUP_ROLES_ROLE_ID_FK FOREIGN KEY
(ROLE_ID) REFERENCES T_ROLES (ID);

-- Tabela T_USER_GROUPS
CREATE OR REPLACE TABLE T_USER_GROUPS
(
  USER_ID INTEGER NOT NULL,
  GROUP_ID INTEGER NOT NULL
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

-- Constraint na FK
ALTER TABLE T_USER_GROUPS
ADD CONSTRAINT CT_USER_GROUPS_USER_ID_FK FOREIGN KEY
(USER_ID) REFERENCES T_USER (ID);

ALTER TABLE T_USER_GROUPS
ADD CONSTRAINT CT_USER_GROUPS_GROUP_ID_FK FOREIGN KEY
(GROUP_ID) REFERENCES T_GROUPS (ID);

-- Tabela T_PRIVILEGES + Sekwencja
CREATE OR REPLACE TABLE T_PRIVILEGES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NAME VARCHAR(20) NOT NULL
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_PRIVILEGES
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_GROUPS
CREATE OR REPLACE TRIGGER TR_PRIVILEGES 
  BEFORE INSERT 
  ON T_PRIVILEGES FOR EACH ROW
BEGIN
  SET NEW.ID = S_PRIVILEGES.NEXTVAL;
END;

-- Unique Constraint 
ALTER TABLE T_PRIVILEGES
ADD CONSTRAINT CT_PRIVILEGES_U UNIQUE (NAME);

-- Tabela T_ROLE_PRIVILEGES
CREATE OR REPLACE TABLE T_ROLE_PRIVILEGES
(
  ROLE_ID INTEGER NOT NULL,
  PRIVILEGE_ID INTEGER NOT NULL
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

-- Constraint na FK
ALTER TABLE T_ROLE_PRIVILEGES
ADD CONSTRAINT CT_ROLE_PRIVILEGES_ROLE_ID_FK FOREIGN KEY
(ROLE_ID) REFERENCES T_ROLES (ID);

ALTER TABLE T_ROLE_PRIVILEGES
ADD CONSTRAINT CT_ROLE_PRIVILEGES_PRIVILEGE_ID_FK FOREIGN KEY
(PRIVILEGE_ID) REFERENCES T_PRIVILEGES (ID);

-- Tabela T_SAVING_TYPES + Sekwencja
CREATE OR REPLACE TABLE T_SAVING_TYPES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  DELETED VARCHAR(1)
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_SAVING_TYPES
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_SAVING_TYPES
CREATE OR REPLACE TRIGGER TR_SAVING_TYPES
  BEFORE INSERT 
  ON T_SAVING_TYPES FOR EACH ROW
BEGIN
  SET NEW.ID = S_SAVING_TYPES.NEXTVAL;
END;

-- Unique Constraint 
ALTER TABLE T_SAVING_TYPES
ADD CONSTRAINT CT_SAVING_TYPES_U UNIQUE (NAME);

-- Tabela T_CURRENCY + Sekwencja
CREATE OR REPLACE TABLE T_CURRENCY
(
  CODE VARCHAR(3) PRIMARY KEY NOT NULL,
  NAME VARCHAR(80) NOT NULL,
  SUFFIX VARCHAR(3) NOT NULL,
  DELETED VARCHAR(1)
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

-- Unique Constraint 
ALTER TABLE T_CURRENCY
ADD CONSTRAINT CT_CURRENCY_U UNIQUE (CODE, NAME, SUFFIX);

-- Tabela T_CURRENCY_RATE + Sekwencja
CREATE OR REPLACE TABLE T_CURRENCY_RATE
(
  ID INTEGER PRIMARY KEY NOT NULL,
  CURRENCY_CODE VARCHAR(3) NOT NULL,
  CURR_RATE DECIMAL(10,4) NOT NULL,
  TIMESTAMP TIMESTAMP
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_CURRENCY_RATE
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_CURRENCY_RATE
CREATE OR REPLACE TRIGGER TR_CURRENCY_RATE
  BEFORE INSERT 
  ON T_CURRENCY_RATE FOR EACH ROW
BEGIN
  SET NEW.ID = S_CURRENCY_RATE.NEXTVAL;
END;

-- Unique Constraint 
ALTER TABLE T_CURRENCY_RATE
ADD CONSTRAINT CT_CURRENCY_RATE_U UNIQUE (CURRENCY_CODE);

-- Tabela T_SAVINGS + Sekwencja
CREATE OR REPLACE TABLE T_SAVINGS
(
  ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID INTEGER NOT NULL,
  SAVING_TYPE_ID INTEGER NOT NULL,
  CURRENCY VARCHAR(3) NOT NULL,
  AMOUNT DECIMAL(19,2) NOT NULL,
  DELETED VARCHAR(1)
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_SAVINGS
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_SAVINGS
CREATE OR REPLACE TRIGGER TR_SAVINGS
  BEFORE INSERT 
  ON T_SAVINGS FOR EACH ROW
BEGIN
  SET NEW.ID = S_SAVINGS.NEXTVAL;
END;

-- Constraint na FK
ALTER TABLE T_SAVINGS
ADD CONSTRAINT CT_SAVINGS_USER_ID_FK FOREIGN KEY
(USER_ID) REFERENCES T_USER (ID);

ALTER TABLE T_SAVINGS
ADD CONSTRAINT CT_SAVINGS_SAVING_TYPE_ID_FK FOREIGN KEY
(SAVING_TYPE_ID) REFERENCES T_SAVING_TYPES (ID);

ALTER TABLE T_SAVINGS
ADD CONSTRAINT CT_SAVINGS_CURRENCY_FK FOREIGN KEY
(CURRENCY) REFERENCES T_CURRENCY (CODE);

-- Tabela T_INCOME_TYPES + Sekwencja
CREATE OR REPLACE TABLE T_INCOME_TYPES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DELETED VARCHAR(1)
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_INCOME_TYPES
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_INCOME_TYPES
CREATE OR REPLACE TRIGGER TR_INCOME_TYPES
  BEFORE INSERT 
  ON T_INCOME_TYPES FOR EACH ROW
BEGIN
  SET NEW.ID = S_INCOME_TYPES.NEXTVAL;
END;

-- Unique Constraint 
ALTER TABLE T_INCOME_TYPES
ADD CONSTRAINT CT_INCOME_TYPES_U UNIQUE (NAME);

-- Tabela T_INCOMES + Sekwencja
CREATE OR REPLACE TABLE T_INCOMES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID INTEGER NOT NULL,
  SAVING_ID INTEGER NOT NULL,
  INCOME_TYPE_ID INTEGER NOT NULL,
  NAME VARCHAR(80),
  CURRENCY VARCHAR(3) NOT NULL,
  AMOUNT DECIMAL(19,2) NOT NULL,
  TIMESTAMP TIMESTAMP
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_INCOMES
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_INCOMES
CREATE OR REPLACE TRIGGER TR_INCOMES
  BEFORE INSERT 
  ON T_INCOMES FOR EACH ROW
BEGIN
  SET NEW.ID = S_INCOMES.NEXTVAL;
END;

-- Constraint na FK
ALTER TABLE T_INCOMES
ADD CONSTRAINT CT_INCOMES_USER_ID_FK FOREIGN KEY
(USER_ID) REFERENCES T_USER (ID);

ALTER TABLE T_INCOMES
ADD CONSTRAINT CT_INCOMES_SAVING_ID_FK FOREIGN KEY
(SAVING_ID) REFERENCES T_SAVINGS (ID);

ALTER TABLE T_INCOMES
ADD CONSTRAINT CT_INCOMES_CURRENCY_FK FOREIGN KEY
(CURRENCY) REFERENCES T_CURRENCY (CODE);


-- Tabela T_EXPENSE_TYPES + Sekwencja
CREATE OR REPLACE TABLE T_EXPENSE_TYPES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DELETED VARCHAR(1)
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_EXPENSE_TYPES
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_EXPENSE_TYPES
CREATE OR REPLACE TRIGGER TR_EXPENSE_TYPES
  BEFORE INSERT 
  ON T_EXPENSE_TYPES FOR EACH ROW
BEGIN
  SET NEW.ID = S_EXPENSE_TYPES.NEXTVAL;
END;

-- Unique Constraint 
ALTER TABLE T_EXPENSE_TYPES
ADD CONSTRAINT CTR_EXPENSE_TYPES_U UNIQUE (NAME);

-- Tabela T_EXPENSES + Sekwencja
CREATE OR REPLACE TABLE T_EXPENSES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID INTEGER NOT NULL,
  SAVING_ID INTEGER NOT NULL,
  EXPENSE_TYPE INTEGER NOT NULL,
  NAME VARCHAR(80),
  CURRENCY VARCHAR(3) NOT NULL,
  AMOUNT DECIMAL(19,2) NOT NULL,
  TIMESTAMP TIMESTAMP
)
ENGINE = INNODB
CHARACTER SET latin2
COLLATE latin2_general_ci;

CREATE OR REPLACE SEQUENCE S_EXPENSES
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE;

-- Trigger TR_EXPENSES
CREATE OR REPLACE TRIGGER TR_EXPENSES
  BEFORE INSERT 
  ON T_EXPENSES FOR EACH ROW
BEGIN
  SET NEW.ID = S_EXPENSES.NEXTVAL;
END;

-- Constraint na FK
ALTER TABLE T_EXPENSES
ADD CONSTRAINT CT_EXPENSES_USER_ID_FK FOREIGN KEY
(USER_ID) REFERENCES T_USER (ID);

ALTER TABLE T_EXPENSES
ADD CONSTRAINT CT_EXPENSES_SAVING_ID_FK FOREIGN KEY
(SAVING_ID) REFERENCES T_SAVINGS (ID);

ALTER TABLE T_EXPENSES
ADD CONSTRAINT CT_EXPENSES_CURRENCY_FK FOREIGN KEY
(CURRENCY) REFERENCES T_CURRENCY (CODE);