/*
 * Skrypt awaryjny, usuwa wszystko ze schematu EWALLET
 */
DROP TABLE IF EXISTS T_EXPENSES;
DROP TABLE IF EXISTS T_INCOMES;
DROP TABLE IF EXISTS T_USER_GROUPS;
DROP TABLE IF EXISTS T_ROLE_PRIVILEGES;
DROP TABLE IF EXISTS T_GROUP_ROLES;
DROP TABLE IF EXISTS T_CURRENCY_RATE;
DROP TABLE IF EXISTS T_ROLES;
DROP TABLE IF EXISTS T_PRIVILEGES;
DROP TABLE IF EXISTS T_GROUPS;
DROP TABLE IF EXISTS T_SAVINGS;
DROP TABLE IF EXISTS T_CURRENCY;
DROP TABLE IF EXISTS T_USER;
DROP TABLE IF EXISTS T_SAVING_TYPES;
DROP TABLE IF EXISTS T_INCOME_TYPES;
DROP TABLE IF EXISTS T_EXPENSE_TYPES;

DROP SEQUENCE IF EXISTS S_EXPENSES;
DROP SEQUENCE IF EXISTS S_INCOMES;
DROP SEQUENCE IF EXISTS S_CURRENCY_RATE;
DROP SEQUENCE IF EXISTS S_GROUPS;
DROP SEQUENCE IF EXISTS S_PRIVILEGES;
DROP SEQUENCE IF EXISTS S_ROLES;
DROP SEQUENCE IF EXISTS S_SAVING_TYPES;
DROP SEQUENCE IF EXISTS S_USER;
DROP SEQUENCE IF EXISTS S_SAVINGS;
DROP SEQUENCE IF EXISTS S_INCOME_TYPES;
DROP SEQUENCE IF EXISTS S_EXPENSE_TYPES;

DROP TRIGGER IF EXISTS TR_EXPENSES;
DROP TRIGGER IF EXISTS TR_INCOMES;
DROP TRIGGER IF EXISTS TR_GROUPS;
DROP TRIGGER IF EXISTS TR_PRIVILEGES;
DROP TRIGGER IF EXISTS TR_ROLES;
DROP TRIGGER IF EXISTS TR_SAVING_TYPES;
DROP TRIGGER IF EXISTS TR_USER;
DROP TRIGGER IF EXISTS TR_SAVINGS;
DROP TRIGGER IF EXISTS TR_INCOME_TYPES;
DROP TRIGGER IF EXISTS TR_EXPENSE_TYPES;